name: islamic_app
description: A Flutter app for displaying prayer timings, mosque events, job postings, and more.

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.20.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  http: ^1.2.2
  json_serializable: ^6.0.1
  provider: ^6.0.5
  flutter_local_notifications: ^18.0.1
  google_maps_flutter: ^2.3.0
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.5.0
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true

  # Commenting assets and fonts to avoid build issues
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
